# bootstrap.ps1 — Windows PowerShell mirror of bootstrap.sh.
#
# Same semantics as scripts/bootstrap.sh (see that file for the spec).
# Modes:
#   .\scripts\bootstrap.ps1           — full bootstrap + write .vis-lock
#   .\scripts\bootstrap.ps1 -Verify   — read-only verify against lock; exit 1 on mismatch

[CmdletBinding()]
param(
    [switch]$Verify
)

$ErrorActionPreference = "Stop"

$PluginDir = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
$VisDir = (Resolve-Path (Join-Path $PluginDir "..")).Path + "\vis"
$VisRepo = if ($env:VIS_REPO) { $env:VIS_REPO } else { "https://github.com/enchanter-ai/vis" }
$VersionsFile = Join-Path $PluginDir ".vis-versions"
$LockFile = Join-Path $PluginDir ".vis-lock"
$ClaudeMd = Join-Path $PluginDir "CLAUDE.md"

function Fail([string]$msg) {
    [Console]::Error.WriteLine($msg)
    exit 1
}

if (-not (Test-Path $VersionsFile)) {
    Fail "missing $VersionsFile — every sibling plugin must pin vis packages"
}
if (-not (Test-Path $ClaudeMd)) {
    Fail "missing $ClaudeMd — bootstrap verifies @-imports against this file"
}

# --- parse .vis-versions --------------------------------------------
$pkgs = @()
$vers = @()
Get-Content $VersionsFile | ForEach-Object {
    $line = ($_ -replace '#.*$', '').Trim()
    if (-not $line) { return }
    if ($line -match '^([a-z]+):\s*"?([~^]?[0-9][^"\s]+)"?\s*$') {
        $pkgs += $matches[1]
        $vers += ($matches[2] -replace '^[~^]', '')
    } else {
        [Console]::Error.WriteLine("warning: unparsed line in .vis-versions: $line")
    }
}

if ($pkgs.Count -eq 0) {
    Fail "no packages parsed from $VersionsFile"
}

# --- ensure vis sibling exists --------------------------------------
if (-not $Verify) {
    if (-not (Test-Path (Join-Path $VisDir ".git"))) {
        [Console]::Error.WriteLine("vis sibling missing at $VisDir — cloning")
        & git clone $VisRepo $VisDir
        if ($LASTEXITCODE -ne 0) { Fail "clone failed — set VIS_REPO or clone manually" }
    }
    & git -C $VisDir fetch --tags --quiet
    if ($LASTEXITCODE -ne 0) { Fail "git fetch --tags failed in $VisDir" }
} else {
    if (-not (Test-Path (Join-Path $VisDir ".git"))) {
        Fail "vis sibling missing — run ./scripts/bootstrap.sh"
    }
}

# --- resolve per-package tag commits ----------------------------------------
$tagCommits = @()
for ($i = 0; $i -lt $pkgs.Count; $i++) {
    $tag = "enchanter-$($pkgs[$i])--v$($vers[$i])"
    $sha = & git -C $VisDir rev-list -n 1 "refs/tags/$tag" 2>$null
    if (-not $sha) {
        Fail "tag missing in vis: $tag"
    }
    $tagCommits += $sha.Trim()
}

$foundSha = (& git -C $VisDir rev-parse HEAD).Trim()

# --- walk CLAUDE.md for @-imports and SHA-1 each ---------------------------
$claudeText = Get-Content $ClaudeMd -Raw
$matches = [regex]::Matches($claudeText, '@\.\./vis/[A-Za-z0-9._/-]+')
$importPaths = $matches | ForEach-Object { $_.Value -replace '^@\.\./vis/', '' } | Sort-Object -Unique

$hashPaths = @()
$hashValues = @()
$missing = $false
foreach ($rel in $importPaths) {
    $full = Join-Path $VisDir $rel
    if (-not (Test-Path $full)) {
        [Console]::Error.WriteLine("import resolves to missing file: @../vis/$rel")
        $missing = $true
        continue
    }
    $h = (Get-FileHash $full -Algorithm SHA1).Hash.ToLower()
    $hashPaths += $rel
    $hashValues += $h
}

if ($missing) {
    Fail "one or more @-imports unresolved — run ./scripts/bootstrap.sh after fixing .vis-versions"
}

# --- write or verify .vis-lock --------------------------------------
function Write-Lock {
    $iso = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")
    $lines = New-Object System.Collections.Generic.List[string]
    $lines.Add("# .vis-lock — auto-generated by scripts/bootstrap.sh")
    $lines.Add("# Do not edit by hand. Run ./scripts/bootstrap.sh to refresh.")
    $lines.Add("vis_commit: $foundSha")
    $lines.Add("resolved_at: $iso")
    $lines.Add("packages:")
    for ($i = 0; $i -lt $pkgs.Count; $i++) {
        $lines.Add("  $($pkgs[$i]):")
        $lines.Add("    version: v$($vers[$i])")
        $lines.Add("    tag_commit: $($tagCommits[$i])")
    }
    $lines.Add("conduct_files:")
    for ($i = 0; $i -lt $hashPaths.Count; $i++) {
        $lines.Add("  - path: $($hashPaths[$i])")
        $lines.Add("    sha1: $($hashValues[$i])")
    }
    Set-Content -Path $LockFile -Value $lines -Encoding ASCII
}

if (-not $Verify) {
    Write-Lock
    Write-Output "bootstrapped: $($pkgs.Count) packages, $($hashPaths.Count) conduct files, vis SHA $foundSha"
    Write-Output "wrote $LockFile"
    exit 0
}

# --verify path
if (-not (Test-Path $LockFile)) {
    Fail "vis not bootstrapped — run ./scripts/bootstrap.sh"
}

$lockText = Get-Content $LockFile -Raw
$lockFound = ([regex]::Match($lockText, '(?m)^vis_commit:\s*(\S+)').Groups[1].Value)
if ($lockFound -ne $foundSha) {
    Fail "vis drift: lock says $lockFound, checkout is $foundSha — run ./scripts/bootstrap.sh to re-resolve"
}

for ($i = 0; $i -lt $pkgs.Count; $i++) {
    $pkg = $pkgs[$i]
    $expected = $tagCommits[$i]
    $rx = "(?ms)^  $([regex]::Escape($pkg)):\s*$.*?^    tag_commit:\s*(\S+)"
    $m = [regex]::Match($lockText, $rx)
    if (-not $m.Success) { Fail "package $pkg missing from lock — run ./scripts/bootstrap.sh" }
    $observed = $m.Groups[1].Value
    if ($observed -ne $expected) {
        Fail "package ${pkg}: lock $observed, checkout $expected — run ./scripts/bootstrap.sh"
    }
}

for ($i = 0; $i -lt $hashPaths.Count; $i++) {
    $rel = $hashPaths[$i]
    $expected = $hashValues[$i]
    $rx = "(?ms)^  - path:\s*$([regex]::Escape($rel))\s*$.*?^    sha1:\s*(\S+)"
    $m = [regex]::Match($lockText, $rx)
    if (-not $m.Success) { Fail "conduct file not in lock: $rel — run ./scripts/bootstrap.sh" }
    $observed = $m.Groups[1].Value
    if ($observed -ne $expected) {
        Fail "conduct file $rel modified since bootstrap — re-bootstrap or revert"
    }
}

Write-Output "verified: $($hashPaths.Count) conduct files, $($pkgs.Count) packages, vis SHA $foundSha"
exit 0
